<?php

/*
 * This file is part of the Telegramm package.
 *
 * (c) Wojciech Nowicki <wojtek@gettelegramm.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Telegramm;

use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * Class Response - UI Response Helper
 *
 * @package Telegramm
 */
class Response extends JsonResponse
{
    public function setData($data = array())
    {
        $data = self::processContent($data);

        return parent::setData($data); // TODO: Change the autogenerated stub
    }

    /**
     * Process output data. Add markup.
     *
     * @param  array|string $content
     * @return array|string
     */
    public static function processContent($content)
    {
        if (is_string($content))
            return preg_replace ('/#([a-z0-9-]+)/i', "<a rel='$1'>#$1</a>", $content);
        if (is_array($content)) {

            foreach ($content as $k => $v) {
                $content[$k] = self::processContent($v);
            }

            return $content;
        }
    }
}
